### ISSUE TITLE
Function future_lapply is using the default value 'future.seed = FALSE'

### ISSUE THREAD

**Issue by adRn-s** [satijalab/sctransform#121]
This gives some warnings when using `future::plan("multicore", workers = 32)` (for example). As a general rule, it is a good practice to test different seed values when fitting models, and this requires the reproducibility of such a stream of numbers.

After reading [this blog post](https://www.r-bloggers.com/2020/09/future-1-19-1-making-sure-proper-random-numbers-are-produced-in-parallel-processing/), and [this manual details](https://future.apply.futureverse.org/reference/future_lapply.html#reproducible-random-number-generation-rng-); I understand that changing the default behavior of this function on `vst.R` and `differential_expression.R` would be a better practice.

**Comment by saketkc** [comment]
This has been [addressed](https://github.com/satijalab/sctransform/commit/cb07ea730c77f173ebb6873ca423a7dbe67b5f1c) in the develop branch. Can you try with `devtools::install_github("satijalab/sctransform", ref="develop")`?

**Comment by adRn-s** [comment]
Thanks for the clarification.

I know it might not be my place to ask for this, but seeing that the latest release is from Dec 16th 2020, I'd like to ask for you to make a new minor release. To me, it is very important to do my analysis with tagged versions, and I'd rather use a proper number than, say, a commit reference.
