### ISSUE TITLE
Doubt Integratedata using normalization SCTransform

### ISSUE THREAD

**Issue by PilanEli** [satijalab/sctransform#138]
Hi,

I'm running the vignette and when I apply the functions for two condictions ( control and tumor)  in the same dataset:

immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, normalization.method = "SCT",
    anchor.features = features)
immune.combined.sct <- IntegrateData(anchorset = immune.anchors, normalization.method = "SCT")

The function integrateData this case with normalization SCtransform be changed to integrate data and keep full geneset (features.to.integrate = to_integrate)?

Thanks

**Comment by PilanEli** [comment]
I got it as follows:
immune.combined.sct <- IntegrateData(anchorset = immune.anchors, (integrated_all_genes = T), normalization.method = "SCT")

I hope I'm right.

**Comment by saketkc** [comment]
I am not sure if I am understanding your question correctly, but by default `IntegrateData` will only integrate the features used in anchor finding. You can provide a custom list of features using `features.to.integrate`, see the documentation [here](https://satijalab.org/seurat/reference/integratedata). For future Integration questions, please open an issue in the Seurat repository.

**Comment by PilanEli** [comment]
Hi

Thank you so much. That was the doubt. I wrote here because I was in doubt for being inside the SCTransform script.

Best regards,
