### ISSUE TITLE
Cannot install sct on macbook pro

### ISSUE THREAD

**Issue by shwetajohari** [satijalab/sctransform#145]
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sctransform.so] Error 1
ERROR: compilation failed for package ‘sctransform’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/sctransform’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/50/9m8p0fvn0mq1l563cshcy3z80000gn/T//Rtmp9Yq4jL/file4de8318469af/sctransform_0.3.4.tar.gz’ had non-zero exit status

**Comment by shwetajohari** [comment]
System: mac os monterey 12.5.1

**Comment by saketkc** [comment]
I would recommend installing brew: https://brew.sh/ and then `brew install gcc` and then installing sctransform.
