### ISSUE TITLE
Error in make_cell_attr(umi, cell_attr, latent_var, batch_var, latent_var_nonreg,  :    cell attribute "log_umi" contains NA, NaN, or infinite value

### ISSUE THREAD

**Issue by LooLipin** [satijalab/sctransform#146]
Hi there,

This is a follow up to my comment on https://github.com/satijalab/sctransform/issues/131#issuecomment-1236497165

I was able to successfully run 7 of my 8 visium samples by following the vignette on https://satijalab.org/seurat/archive/v3.2/spatial_vignette.html

Unfortunately, one failed at the scTransform stage with Error in make_cell_attr(umi, cell_attr, latent_var, batch_var, latent_var_nonreg,  : cell attribute "log_umi" contains NA, NaN, or infinite value

I tried to upload my object but it is slightly over the limit. Can you please provide me with an email to forward?

Thanks,
Lipin

**Comment by saketkc** [comment]
You can email me at schoudhary@nygenome.org

**Comment by saketkc** [comment]
One of your cell has no UMIs:

```r
> min(obj$nCount_Spatial)
0
```

You can filter the cell out:

```r
obj <- subset(obj, nCount_Spatial>0)
```

and then run SCTransform:

```r
obj <- SCTransform(obj, assay="Spatial")
```
