### ISSUE TITLE
Please specify Matrix version with equal separation signs

### ISSUE THREAD

**Issue by tillea** [satijalab/sctransform#148]
Hi,
I'm aware that in R the signs '.' and '-' are sorting equally in version numbers.  This is not true for Debian package versions und thus for the latest Debian package I needed the [following patch](https://salsa.debian.org/r-pkg-team/r-cran-sctransform/-/blob/master/debian/patches/fix_matrix_version_string.patch):

    -Imports: dplyr, magrittr, MASS, Matrix (>= 1.5.0), methods,
    +Imports: dplyr, magrittr, MASS, Matrix (>= 1.5-0), methods,

for the version of Matrix.  It would be extremely helpful if you would simply keep the same spelling for version numbers as the authors of a package have decided for.
Kind regards, Andreas.

**Comment by saketkc** [comment]
Thanks for reporting this and for the patch. I will fix this in the next release.

**Comment by tillea** [comment]
Am Mon, Sep 26, 2022 at 04:57:29PM -0700 schrieb Saket Choudhary:
> Thanks for reporting this and for the patch. I will fix this in the next release. 
Thanks a lot for your cooperation, Andreas.

**Comment by tillea** [comment]
Hi,
unfortunately in version 0.4.0 the issue persists.  I can patch it again inside the Debian package, but it would be great if you could commit a fix to Git to close this issue.
Thanks a lot, Andreas.

**Comment by tillea** [comment]
Am Tue, Oct 17, 2023 at 05:15:29AM -0700 schrieb Saket Choudhary:
> Apologies that I missed this in the latest release. For now I would recommend patching it at your end and will incorporate the fix in the next release.

I've done so, yes.  I'd simply recommend you push a fix to Git and close this issue to make sure it gets fixed next time. ;-)
Kind regards, Andreas.

**Comment by saketkc** [comment]
Fixed in develop branch, thanks!
