### ISSUE TITLE
combining incrementally available data

### ISSUE THREAD

**Issue by e-manduchi** [satijalab/sctransform#149]
Hello SCTransform and Seurat Team,

I'd appreciate your advice on a special situation we are in.
We have an established reference (from multiome data) that has allowed us to annotate cell types from a particular tissue.

We are now incrementally getting new scRNA-seq data from the same tissue type from different individuals (sometimes months apart between groups of individuals). We are considering the following incremental approach. Process the scRNAseq data from each individual separately as they become available, obtaining its SCTransformed counts. At the same time we can annotate cells for this individual by mapping to our established reference.

Having the above, do you see any issue in doing DE analyses (e.g. for a given cell type between different conditions for these individuals) using as input the separately computed SCRTransformed counts? E.g. deriving pseudobulk counts for each individual from its SCTransformed counts and then inputting the pseudobulk counts into DESeq2 or similar programs, properly accounting for relevant covariates (sex, ethnicity, library reagent kit used, etc.) in our analyses. This is just an example; non-pseudobulk analyses could be an alternative. The main point though is that we wouldn't be doing any integration in addition to that done once for each individual when annotating its cell types using the reference.

Thanks for your attention

**Comment by saketkc** [comment]
Your workflow sounds reasonable with one caveat. SCTransform corrected counts are calculated by reversing the regression model by substituting median sequencing depth. If the sequencing depth is very different across samples, this would result in inflated false positives. In the [SCT v2 vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) we show how to correct for such diferences by using `PrepSCTFindMarkers()` which will readjust corrected counts to be at the same sequencing depth across samples. You can then use standard DE methods (wilcox/LR/mast) on the corrected counts.

**Comment by e-manduchi** [comment]
Thank you so much for the advice!
Elisabetta
