### ISSUE TITLE
Data visualization and differential gene expression after SCT normalization and integration

### ISSUE THREAD

**Issue by yuyuliu** [satijalab/sctransform#151]
Hi, I know that similar questions have been asked many times, and I swear I read most of the issues and answers, but I am still confused in some points.

First, I understood that SCT performs normalization and returns the SCT assay containing centered Pearson residuals in scale.data slot, that were then converted to sequencing depth corrected UMI counts stored in counts slot, and these counts were log-normalized and stored in data slot.

After I performed integration of 3 SCT normalized data, I obtain a new assay named "integrated".  This assay also contains a scale.data slot and data slot.

So here, if I want to visualize the normalized data and compare expression levels between different samples, should I use the scale.data slot or data slot? from the SCT assay or integrated assay?
Most of the issues and answers that I found said that these kind of analysis will be able on the upcoming Seurat v3.
But the current version is v4, and you provided a [vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) applying FindMarkers on the data slot of SCT assay for identification of differentially expressed genes. Is this the right way to perform such analysis?

I compared the violin plots obtained from 1) scale.data of SCT assay, 2) data of SCT assay, 3) scale.data of integrated assay, and 4)data of integrated assay for a same gene, but the 4 plots look completely different.
I am so confused.
![ex](https://user-images.githubusercontent.com/11191404/205869580-7b65b39c-9920-445f-a80e-1af449af151f.png)

**Comment by saketkc** [comment]
You should use the `data` slot of the SCT assay for visualization - it contains `log1p(corrected counts)` that has been adjusted for differences in sequencing depth.
