### ISSUE TITLE
Questions about finding different gene-peak links based on rna and sct (related to sctransform)

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/sctransform#156]
Hi all, I contact two seperated datasets to generate the overall gene-peak link result. However, I found that the results I have based on RNA in the idenfitifcation process are very differernt from the results based on SCT. For two datasets, is it ok for me to directly contact them? Thanks.

**Comment by saketkc** [comment]
The gene-peak link functionality is part of [Signac](https://github.com/stuart-lab/signac). 

Based on whoch assay you chose the links can vary across the two assays because of the different nature of normalization (LogNorm vs SCT). You would want to stick to one method across the datasets.

**Comment by HelloWorldLTY** [comment]
Hi, for all the datasets I used, they follow the pipeline of SCT. For all the datasets we used to detect the link, we used SCT. Therefore, my question is , if I combine two datasets processed by SCT to one array, the number of links I found is quite large and different from the number of links I found based on LogNorm. Thanks.
