### ISSUE TITLE
Sctransform with multiple samples per batch

### ISSUE THREAD

**Issue by ConDem94** [satijalab/sctransform#157]
Hi,

Thank you so much for this amazing normalization tool. I would like to ask, I am currently trying to integrate 5 studies (batches) with varying number of samples (pancreatic cancer). I saw that some samples have lower sequencing depth than others following my QC filtering step.

Therefore, should I perform sctransform per sample, per batch or the merged dataset (all 5 studies, 68 samples). 

Thank you!

BW,
Constantinos

**Comment by saketkc** [comment]
We recommend running sctransform per sample followed by integration.
