### ISSUE TITLE
Questions about errors in the sctransform for selected genes

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/sctransform#158]
![image](https://user-images.githubusercontent.com/43333475/217697878-97cc0e98-0399-4b70-90c6-697816cdfa05.png)
Hi, I select 1000 genes here for sctransform, but the return data only contain 999 genes. I believe that there are some bugs. Could you please help me? Thanks a lot.

**Comment by saketkc** [comment]
You should run SCTransform as `SCTransform(vst.flavor="v2", variable.features.n =1000)`.
