### ISSUE TITLE
Subscript out of bounds and tcrossprod

### ISSUE THREAD

**Issue by noob-aid** [satijalab/sctransform#159]
Hello,

I'm trying to run `vst` on a very small matrix of ~1500 genes x 20 cells. It throws the following error at the second step:

```
Second step: Get residuals using fitted parameters for 1586 genes
  ||   0%Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'tcrossprod': subscript out of bounds
```

Is the error due to the fact that the input is a very small dataset? I should also note that the values are positive but non-integer. Thanks in advance for your help.

**Comment by saketkc** [comment]
Can you try with `vst.flavor="v2"`?

**Comment by saketkc** [comment]
If it is just 1500 genes, can you upload the matrix here?

**Comment by saketkc** [comment]
Thanks for sharing the object. Some genes names start with special characters (";", ","). I was able to run `vst()` after fixing the rownames:

```r
obj <- readRDS("test.RDS")
rownames(obj) <- paste0("gene", rownames(obj))
vst.out <- vst(obj)
```
