### ISSUE TITLE
Using counts from 'SCT' assay and 'data' slot for trajectory analysis

### ISSUE THREAD

**Issue by reneemoerkens** [satijalab/sctransform#164]
Dear SCTransform development team,

After transforming my scRNAseq dataset using SCTransform v2 (according to the vignette: https://satijalab.org/seurat/articles/sctransform_v2_vignette.html), can I now use the count matrix from 'SCT' assay and 'data' slot for trajectory analysis (such as PAGA, scVelo, CellRank)?

Thank you!

**Comment by saketkc** [comment]
I think this question would be more suited to scVelo/CellRank authors.
