### ISSUE TITLE
Why $SCT assay during differential expression analysis?

### ISSUE THREAD

**Issue by Ryuzaman** [satijalab/sctransform#165]
Hello there! 
I have a question regarding data integration using SCTransform. 
The integration paper states that the $integrated assay data can be used for downstream analysis such as dimensionality reduction and clustering. Intuitively, I feel that for differential expression analysis, we should use the data with batch effect removed using anchors ($integrated). However, in the tutorial, it mentions using the data from $SCT assay for visualization and differential expression analysis. 
I would like to know if there are any specific reasons to use the $SCT assay data. I did come across a previous issue suggesting the use of $SCT, but it did not mention the reasons behind it. Or, if there is any existing paper that addresses this, please let me know.
Sincerely, 
Ryuzaman

**Comment by saketkc** [comment]
It is covered on multiple issues on the seurat repo:

https://github.com/satijalab/seurat/discussions/5452
https://github.com/satijalab/seurat/discussions/4000

**Comment by Ryuzaman** [comment]
Thanks!
