### ISSUE TITLE
FindAllMarkers on SCT V1 assay or RNA on a single sample (non-integrated)?

### ISSUE THREAD

**Issue by fahmadimoughari** [satijalab/sctransform#168]
Hi,

I am using SCTransform V1 on individual samples (no integration is supposed to be done). When I wanted to find the markers of clusters within a sample that has been normalized using SCTransform V1, should I go back to RNA assay or use SCT assay for differential expression analysis (FindAllMarkers)?

Regards,
Fatemeh

**Comment by saketkc** [comment]
You should still be able to use 'PrepSCTFindMarkers' to perform DE using the SCT assay. I would recommend installing the latest develop branch of Seurat where we have introduced substantial speedup to that function.

**Comment by fahmadimoughari** [comment]
Hi Saket,

Thanks for your quick reply. As I understood 'PrepSCTFindMarkers' should be run on the merged object, where we have different samples in one object. But What I was asking for was a single object containing a single sample. Do I still need to run 'PrepSCTFindMarkers' before DE analysis?

**Comment by saketkc** [comment]
Right, you don't need to run PrepSCTFindmarkers if you have one sample (your initial post seems to suggest otherwise). It won't do any changes even if you were to run it.

**Comment by fahmadimoughari** [comment]
Thank you, Saket. I appreciate your help. Can you help me with my main question: Considering that this is an object contacting only one sample and I ran SCTransform V1, which slot shall I use for DE analysis? SCT or RNA?

**Comment by fahmadimoughari** [comment]
I am grateful for your help, Saket
. Just have a slight confusion regarding your answer. I can infer three meanings from it:
-  SCT is"OKAY" to be used for DE analysis, and also "RNA" is OKAY to be used for DE analysis.
- second meaning: SCT  is "BETTER" to be used in comparison to RNA for DE analysis
- third meaning: SCT is the only correct slot to be used for DE analysis.

Sorry for asking many questions, I really appreciate your time.

**Comment by saketkc** [comment]
In the v2 paper we show clear advantages of using the SCT assay. That said, it is not incorrect to use the RNA assay as long as you have run  NormalizeData. Hope this helps.

**Comment by fahmadimoughari** [comment]
I know that SCT V2 is much better to be used both for normalization and DE analysis, but for some reason, we decided to try SCT V1, My question was in the case of using SCTransform ""V1"", which slot is the right slot for DE analysis?

**Comment by saketkc** [comment]
You should use the data slot when using SCT assay.

**Comment by saketkc** [comment]
I would recommend using SCT assay but in such scenarios it is not a bad idea to run both.
