### ISSUE TITLE
ERROR: `assay` must be one of "SCT" or "integrated", not "RNA"

### ISSUE THREAD

**Issue by osmanmerdan** [satijalab/sctransform#177]
I have an integrated Seurat object, `integrated,` which has two assays: `integrated` and `SCT.` It does not contain an `RNA` assay because I have deleted it to save some space. I have run:

`integrated <- PrepSCTFindMarkers(integrated)`. 

Returned error:  `assay` must be one of "SCT" or "integrated," not "RNA." 
How can I solve this issue? Is there anyone who encountered a similar error?

**Comment by saketkc** [comment]
Hi @osmanmerdan, you need the RNA assay to be present for running `PrepSCTFindMarkers` as the raw UMIs are necessary for calculating the corrected counts. Can you try again? I will have PrepSCTFindMarkers emit better error message in the future.
