### ISSUE TITLE
Understanding the purpose of corrected counts

### ISSUE THREAD

**Issue by danielcgingerich** [satijalab/sctransform#179]
Trying to understand what exactly corrected counts are.  I do not see how the corrected counts are different than the raw count matrix.  Ive looked at the source code for correct_counts in this repository and identify the source of my misunderstanding. 
from line 237 in denoise.R
```
mu <- exp(tcrossprod(coefs, regressor_data_orig))
variance <- mu + mu^2 / theta
y <- as.matrix(umi[genes_bin, , drop=FALSE])
pearson_residual <- (y - mu) / sqrt(variance)
# generate output
mu <- exp(tcrossprod(coefs, regressor_data))
variance <- mu + mu^2 / theta
y.res <- mu + pearson_residual * sqrt(variance)
```

 mu + pearson_residual * sqrt(variance) = mu + (y - mu) / sqrt(variance) * sqrt(variance) = mu + y - mu = y. 

Whats the purpose of this?

**Comment by saketkc** [comment]
This is explained in the [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02584-9). Briefly, the idea is to put all the cells to same sequencing depth (median) and then ask what would be observed counts (with minimal technical variation or mostly biological variance) given the model captures technical variation.

**Comment by danielcgingerich** [comment]
@saketkc Thank you!
