### ISSUE TITLE
Working back to raw counts from corrected counts?

### ISSUE THREAD

**Issue by abussing** [satijalab/sctransform#185]
### My issue

I am trying to use the parameters from the GLM to work backwards from corrected counts $y_{gc}$ to raw counts $x_{gc}$.

### Main idea

In the sctransform v2 paper, it says the corrected counts $y_{gc}$ are created by:

$$
y_{gc} = \text{floor}\left(\frac{x_{gc}-\mu_{gc}}{\sigma_{gc}} \sigma_{gc}^{'} + \mu_{gc}^{'} \right)
$$

which means we can say that 

$$
y_{gc} \leq \frac{x_{gc}-\mu_{gc}}{\sigma_{gc}} \sigma_{gc}^{'} + \mu_{gc}^{'} < y_{gc} + 1
$$

which further implies

$$
\left(y_{gc} - \mu_{gc}^{'}\right)\frac{\sigma_{gc}}{\sigma_{gc}^{'}} + \mu_{gc} \leq x_{gc} < \left(y_{gc} + 1 - \mu_{gc}^{'}\right)\frac{\sigma_{gc}}{\sigma_{gc}^{'}} + \mu_{gc}
$$

and thus we have found an inequality that contains the raw counts $x_{gc}$.

### Implementing in R

The $\mu_{gc}$, $\mu_{gc}^{'}$, $\sigma_{gc}$, $\sigma_{gc}^{'}$ from the above expressions are defined as:

$$
\begin{aligned}
\mu_{gc} &= \exp\left(\beta_{g0} + \ln(n_c)\right) \\
\mu_{gc}^{'} &= \exp\left(\beta_{g0} + \ln(n_0)\right) \\
\sigma_{gc} &= \sqrt{\mu_{gc} + \frac{\mu_{gc}^2}{\theta_g}}\\
\sigma_{gc}^{'} &= \sqrt{\mu_{gc}^{'} + \frac{{\mu_{gc}^{'}}^2}{\theta_g}}
\end{aligned}
$$

where $n_c = \sum_{g}x_{gc}$ and $n_0 = \text{median}\left(n_c\right)$. 

$\beta_{g0}$, $\theta_g$, $n_c$, and $n_0$ are stored in the following locations of the sctransformed seurat object:

```
beta_g0 <- pbmc@assays$SCT@SCTModel.list$counts@feature.attributes$`(Intercept)`
theta_g <- pbmc@assays$SCT@SCTModel.list$counts@feature.attributes$theta
n_c <- pbmc@meta.data$nCount_RNA
n_0 <- median(pbmc@meta.data$nCount_RNA)
```

and so we have everything we need to calculate the inequality defined above.

### Results

Now we apply this to the pmbc_small data set:

```
pbmc_sub <- Seurat::SCTransform(pbmc_sub, assay = "RNA")

undone_counts <- undo_counts(corrected_counts = pbmc_small@assays$SCT$counts,
                             feature.attributes = pbmc_small@assays$SCT@SCTModel.list$model1@feature.attributes,
                             cell.attributes = pbmc_small@assays$SCT@SCTModel.list$model1@cell.attributes) 
```

here is a look at 10 cells of gene LGALS1:

![github_pic](https://github.com/satijalab/sctransform/assets/101529275/b0b9baef-b6e8-4de0-8788-70afc0aedf45)

our bounds are doing an okay job, but I am wondering why they are not always containing the true value between them?

**Comment by saketkc** [comment]
Thanks for your question. The corrected counts in the SCT assay by default use median of the sequencing depth (median(nCount_RNA)) as the scaling factor. For this inequality to hold overall, you would need to scale each cell to its original sequencing depth which would IMO defeat the purpose of 'correcting' the counts. Hope this helps!

**Comment by abussing** [comment]
> Thanks for your question. The corrected counts in the SCT assay by default use median of the sequencing depth (median(nCount_RNA)) as the scaling factor. For this inequality to hold overall, you would need to scale each cell to its original sequencing depth which would IMO defeat the purpose of 'correcting' the counts. Hope this helps!

Thanks for your response. Can you explain which step of my process is incorrect? The inequality is derived directly from the definition of $y_{gc}$ using simple algebra.

**Comment by saketkc** [comment]
Corrected counts `pbmc_small@assays$SCT$counts` are caculated on the median(nCount) value. 
https://github.com/satijalab/sctransform/blob/8efb6929b4dd6da9c0849b5a19380e8fd0c4baeb/R/denoise.R#L83
