### ISSUE TITLE
Issue with calling "glmGamPoi" to work

### ISSUE THREAD

**Issue by Joy8Liu** [satijalab/sctransform#192]
Hi, there is a issue I've encountered when using sctransform. I'd like to ask this problem for help.
I've installed 'glmGamPoi', and the answer to `'glmGamPoi' %in% installed.packages()` is True.

But when I run the code `Pre3 <- SCTransform(Pre3, verbose = FALSE)`, 
The response is the following information:

```
`vst.flavor` is set to 'v2' but could not find glmGamPoi installed.
Please install the glmGamPoi package for much faster estimation.
--------------------------------------------
install.packages('BiocManager')
BiocManager::install('glmGamPoi')
--------------------------------------------
Falling back to native (slower) implementation.
```

I wonder how I can resolve this problem. Thank you so much for your help in advance.

_Originally posted by @Joy8Liu in https://github.com/satijalab/seurat/issues/5585#issuecomment-2095827086_

**Comment by Joy8Liu** [comment]
Find a solution already, never mind.

**Comment by cgorozco** [comment]
What was the solution?

**Comment by cgorozco** [comment]
What was the solution?

**Comment by Joy8Liu** [comment]
I couldn't remember it clearly. But the reason is one dependency of "glmGampoi" is not installed. I seemed to find this dependency by the Error occurred when I `library(glmGamPoi)`? So someone may find hints from the error message.

**Comment by Joy8Liu** [comment]
> What was the solution?

I couldn't remember it clearly. But the reason is one dependency of "glmGampoi" is not installed. I seemed to find this dependency by the Error occurred when I library(glmGamPoi)? So someone may find hints from the error message.
