### ISSUE TITLE
scTransform failed without giving errors 

### ISSUE THREAD

**Issue by jingsday** [satijalab/sctransform#198]
Hello bioinformaticians,

I was wondering if you could provide any insights regarding me failing to run scTransform. It is 'An object of class Seurat 
27475 features across 57058 samples within 1 assay' and all went well until it suddenly quit without any errors in the log.

_nohup.out_ 
Active assay: RNA (27475 features, 0 variable features)
 16 layers present: counts.1, counts.2, counts.3, counts.4, counts.5, counts.6, counts.7, counts.8, counts.9, counts.10, counts.11, counts.12, counts.13, counts.14, counts.15, counts.16
Running SCTransform on assay: RNA
Running SCTransform on layer: counts.1
....
Integrating data
Merging dataset 2 4 13 5 7 into 11 16 1 3 15 6 10 9
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
This is the last line. 

SCTransform part of the script:
#Part II: SCT intergration and save files for furthur analysis

obj.list <- lapply(X = obj.list, FUN = SCTransform)
features <- SelectIntegrationFeatures(object.list = obj.list, nfeatures = 3000)
obj.list <- PrepSCTIntegration(object.list = obj.list, anchor.features = features)

anchors <- FindIntegrationAnchors(object.list = obj.list, normalization.method = "SCT",
                                  anchor.features = features)
seurat.integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT")

seurat.integrated <- ScaleData(object = seurat.integrated)
seurat.integrated <- RunPCA(object = seurat.integrated)
seurat.integrated <- RunUMAP(object = seurat.integrated, dims = 1:50)

I appreciate your attention and any comments.

Regards,
Jing

**Comment by saketkc** [comment]
Hi @jingsday, I do not see any error in the SCTransform step (or other steps), so would recommend that you open an issue on the seurat repo.
