### ISSUE TITLE
Converting `scale.data` layer for scTransform to sparce matrix

### ISSUE THREAD

**Issue by siegelna** [satijalab/sctransform#199]
I am aware that using SCT for normalization of single-cell data is considered best practice, however plotting violin plots after normalization with SCT results in discrete values plotted (see below). The `scale.data` layer contains the expression level that people are more accustomed to viewing. Unfortunately, when SCT is run without excluding non-variable genes the object becomes huge. This is due to the layer not being stored as sparce matrix. 

**Are there any negative repercussions with converting the non-sparce matrix into sparce and then replacing it with the original `scale.data` layer?**

 **Standard normalization**

![image](https://github.com/user-attachments/assets/26d370cf-7d76-4a6a-b5a4-ae672d9f945e)

**SCT normalization**

![image](https://github.com/user-attachments/assets/4015a432-572b-48d6-9a58-717c32851e82)

**Comment by saketkc** [comment]
`scale.data` layer of SCT should not be used for visualization as these are pearson residuals.
