### ISSUE TITLE
Consider standard lapply when there is no parallel processing

### ISSUE THREAD

**Issue by jgarthur** [satijalab/sctransform#201]
Since `future_lapply` is used in `get_model_pars` even when `n_workers == 1`, the user needs to adjust `future.globals.maxSize` depending on the dataset, which is tricky for incorporating `sctransform` into a pipeline. I would also worry that `future_lapply` is unnecessarily copying a lot of memory. Could the standard `lapply` be substituted instead when there is only 1 worker?

**Comment by saketkc** [comment]
Thanks Joey! I have been myself hitting this lately - will fix it!

**Comment by saketkc** [comment]
Hi @jgarthur the changes are on develop [branch](https://github.com/satijalab/sctransform/commit/515beacfcd53a9a3a561cb648e0f498c24ee9244) I will make a release soon.
